apiVersion: v1 
kind: Service
metadata:
  name: edge-service 
spec:
  selector:
    app: edge
  type: LoadBalancer
  ports:
    - name: socket
      port: 5001
      targetPort: 5001
      nodePort: 30235
    
