apiVersion: batch/v1
kind: Job
metadata:
  name: run-once-job-edge
spec:
  template:
    spec:
      containers:
      - name: run-once-job-edge
        image: ismailshojeeb/edge:v12
        command: ["python", "sub_with_time.py"]
        ports:
        - containerPort: 5005
      restartPolicy: Never
  backoffLimit: 0
