# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install flask pandas scikit-learn

# Make port 5005 available to the world outside this container
EXPOSE 5005

# Run the Python script when the container launches
CMD ["python", "cloud.py"]