# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libatlas-base-dev \
    gcc \
    gfortran \
    cmake \
    && apt-get clean

# Copy the current directory contents into the container at /app
COPY . /app

# Upgrade pip
RUN pip install --upgrade pip

# Install Python dependencies
RUN pip install paho-mqtt requests pandas scikit-learn flask

# Expose the port the app runs on
EXPOSE 5005

# Run the Python script when the container launches
CMD ["python", "fog.py"]
