apiVersion: batch/v1
kind: Job
metadata:
  name: run-once-job-edge
spec:
  template:
    spec:
      containers:
      - name: run-once-container-edge
        image: ismailshojeeb/edge:v10
        command: ["python", "sub.py"]
      restartPolicy: Never
  backoffLimit: 0
