apiVersion: v1 
kind: Service
metadata:
  name: cloud-service 
spec:
  selector:
    app: cloud
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30234
    
